### PR TITLE
Move options to observe()

### LINKED ISSUE #259: Move Options to observe?
If we want to do that, we should do it now.

Spec wise this should be easy

@arskama would this be hard implementation wise?

Do we recall why we move it to the ctor?

ResizeObserver, PerformanceObserver, MutationObserver has it as part of observe:

```js
undefined observe(Node target, optional MutationObserverInit options = {});
undefined observe(Element target, optional ResizeObserverOptions options = {});
undefined observe(optional PerformanceObserverInit options = {});
```

### PR DESCRIPTION
**Pull request by kenchris**
Fixes #259

***
<a href="https://pr-preview.s3.amazonaws.com/kenchris/compute-pressure/pull/261.html" title="Last updated on Apr 5, 2024, 11:07 AM UTC (79e0d95)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/compute-pressure/261/42f1fcd...kenchris:79e0d95.html" title="Last updated on Apr 5, 2024, 11:07 AM UTC (79e0d95)">Diff</a>

### CODE REVIEW

**Comment by arskama** [comment]
LGTM, Would be good to have another reviewer on that one as well.

**Review by tomayac — COMMENTED** [review]
The changes need to be reflected in the Explainer as well (two instances).

Do I read it correctly that the `sampleInterval` if no value is given is set to `0`? What does this mean? That it will never run?

**Comment by kenchris** [comment]
@tomayac Arnaud has another PR up for changing the explainer etc.

If it is 0, it will get as fast as the system can handle:

> If timeDeltaMilliseconds ≥ sampleInterval, return true, otherwise return false.

We could consider using something else, mind filing an issue?

**Comment by darktears** [comment]
LGTM.

**Comment by kenchris** [comment]
https://wicg.github.io/periodic-background-sync/#periodic-sync-registration-minimum-interval <- also uses minInterval of 0 (as fast as system allows)

https://wicg.github.io/js-self-profiling/#the-profilersample-dictionary says it must be 0 or bigger, but doesn't even check whether it is not undefined

**Comment by kenchris** [comment]
Yes, for the same source type that makes sense, but we need to spec things differently when we support multiple sources. We do that now in the spec, but makes sense to postpone till after shipping

**Pull request merged**
