### PR TITLE
setup streamlined publication

### LINKED ISSUE #169: Enable automatic WD publication
Decision: https://lists.w3.org/Archives/Public/public-device-apis/2021May/0008.html

Depends on https://github.com/WICG/wicg.github.io/pull/21

### PR DESCRIPTION
**Pull request by himorin**
closes #169

Do we want to add [W3C_NOTIFICATIONS_CC](https://github.com/w3c/spec-prod/blob/main/docs/options.md#w3c_notifications_cc) to get email for e.g. noticing errors?

***
<a href="https://pr-preview.s3.amazonaws.com/himorin/w3c-compute-pressure/pull/174.html" title="Last updated on Dec 23, 2022, 5:25 AM UTC (5b466ce)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/compute-pressure/174/d74f5a1...himorin:5b466ce.html" title="Last updated on Dec 23, 2022, 5:25 AM UTC (5b466ce)">Diff</a>

### CODE REVIEW

**Comment by himorin** [comment]
[23896b8](https://github.com/w3c/compute-pressure/pull/174/commits/23896b865f0de52687f7d9129e371dfa7ff3d2e3) is for html validation fix on recently imposed ones, [5b466ce](https://github.com/w3c/compute-pressure/pull/174/commits/5b466ced35dd23788e2a5a1db675448ea10b23dd) is to dealt with limitation of html validator (seems cannot handle out-BMP chars in CSS??)

**Comment by kenchris** [comment]
@anssiko is this something you can review?

**Review by anssiko — APPROVED** [review]

**Comment by anssiko** [comment]
@kenchris @arskama this enables automatic publication to https://www.w3.org/TR/compute-pressure/

Should you run into issues, @himorin will be able to assist you. Thanks @himorin for setting this up.

**Comment by himorin** [comment]
I will, for monitoring GHActions' error.

**Pull request merged**
