### PR TITLE
Use same origin checks instead of same origin-domain ones

### LINKED ISSUE #187: Does the privacy test need a same origin-domain or a same origin check?
In other words, do we need to check for https://html.spec.whatwg.org/multipage/browsers.html#same-origin or https://html.spec.whatwg.org/multipage/browsers.html#same-origin-domain?

AFAICS the latter (which we currently use) just takes `document.document` into consideration compared to the "same origin" check.

I am not informed enough to know which to choose, so this is an honest question. Looking at https://dontcallmedom.github.io/webdex/s.html, "same origin-domain" is used by fewer specs, and https://bugs.chromium.org/p/chromium/issues/detail?id=1027191#c6 says _"Specs use 'same origin' in pretty much all cases except where forced to otherwise for compat reasons.  On particular, any modern spec is likely to not use 'same origin-domain' at all"_.

### PR DESCRIPTION
**Pull request by arskama**
Fixes #187

***
<a href="https://pr-preview.s3.amazonaws.com/arskama/compute-pressure/pull/236.html" title="Last updated on Oct 2, 2023, 5:27 AM UTC (218a80b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/compute-pressure/236/2847760...arskama:218a80b.html" title="Last updated on Oct 2, 2023, 5:27 AM UTC (218a80b)">Diff</a>

### CODE REVIEW

**Comment by arskama** [comment]
Please add reviewers if you think we might need.

**Review by kenchris — APPROVED** [review]
Would have been good with a more descriptive commit message

**Comment by arskama** [comment]
> Would have been good with a more descriptive commit message

I ll change it when merging

**Comment by arskama** [comment]
@kenchris How about:

"
From different source [1][2][3], it looks like same origin-domain is not anymore recommended.
There is no obvious reason to keep same origin-domain in compute pressure specification.
 Instead same origin seems to be a better security check.

[1] https://html.spec.whatwg.org/multipage/browsers.html#relaxing-the-same-origin-restriction
[2] https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/weborigin/security_origin.h;l=313;drc=933be5e5db24585647edcd7f507ba2d48c5757c8
[3] https://dontcallmedom.github.io/webdex/s.html
"

**Review by rakuco — APPROVED** [review]
lgtm too

In addition to improving the PR/commit message, please use a better title too: "fix A to B" is not a very usual construct. How about something like "Use same origin checks instead of same origin-domain ones"?

**Pull request merged**
