### PR TITLE
Fix nits

### PR DESCRIPTION
**Pull request by beaufortfrancois**
@arskama PTAL

### CODE REVIEW

**Comment by anssiko** [comment]
(FYI, the failing check is being addressed by https://github.com/w3c/devicesensors-wg/issues/64)

**Review by arskama — APPROVED** [review]
Thanks for the commit. LGTM

**Comment by anssiko** [comment]
https://github.com/w3c/devicesensors-wg/issues/64 has been fixed and now all the checks pass. This is ready to merge.

**Comment by anssiko** [comment]
@beaufortfrancois thanks for these improvements to the example code! It is extremely important to get the details of these examples right.

Quoting Joshua Bloch:

>Example code should be exemplary. If an API is used widely, its examples will be the archetypes for thousands of programs. Any mistakes will come back to haunt you a thousand fold.

Your contribution will ensure the early adopters of this API will get it right from the beginning.

I will merge this PR now. Please note your contributions will appear at the canonical spec URL https://www.w3.org/TR/compute-pressure/ when the automatic publication has been enabled (tracked in https://github.com/w3c/compute-pressure/issues/169). Meanwhile, https://w3c.github.io/compute-pressure/ reflects the latest.

**Pull request merged**
